version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - neolitec
  - whispyy
  ignore:
  - dependency-name: polished
    versions:
    - 4.1.0
    - 4.1.1
  - dependency-name: react-native-screens
    versions:
    - 2.17.1
    - 2.18.0
    - 2.18.1
    - 3.0.0
    - 3.1.0
  - dependency-name: "@react-navigation/native"
    versions:
    - 5.9.2
    - 5.9.3
  - dependency-name: "@react-navigation/stack"
    versions:
    - 5.14.2
    - 5.14.3
